// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace VerhuisHulp.Migrations
{
    [DbContext(typeof(VerhuisHulpContext))]
    partial class VerhuisHulpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VerhuisHulp.Models.DeadlineItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("DeadlineItem");
                });

            modelBuilder.Entity("VerhuisHulp.Models.TodoItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeadlineItemId");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDone");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineItemId");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("VerhuisHulp.Models.TodoItem", b =>
                {
                    b.HasOne("VerhuisHulp.Models.DeadlineItem")
                        .WithMany("TodoItems")
                        .HasForeignKey("DeadlineItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
